[platformio]
default_envs = esp01_1m

[common]
lib_deps =
  bblanchon/ArduinoJson@^7.1.0

build_flags =
  -std=gnu++17
  -D FM_WAIT_COMMAND_PATH=\"/api/device/wait-command\"
  -D FM_COMMAND_RESULT_PATH=\"/api/device/command-result\"
  -D FM_MAX_RELAY_PULSE_MS=3000
  -D FM_WIFI_CONNECT_TIMEOUT_MS=30000
  -D FM_RECONNECT_JITTER_MIN_MS=100
  -D FM_RECONNECT_JITTER_MAX_MS=500
  -D FM_NTP_SERVER_1=\"pool.ntp.org\"
  -D FM_NTP_SERVER_2=\"time.nist.gov\"
  -D FM_NTP_SERVER_3=\"time.google.com\"
  -D FM_DEFAULT_POLL_TIMEOUT_MS=60000
  -D FM_DEFAULT_HTTP_TIMEOUT_MS=70000
  -D FM_ROOT_CA_WARN_BEFORE_DAYS=90
  -D FM_ALLOW_INSECURE_TLS_AFTER_CA_EXPIRE=1

[relay_esp01]
build_flags =
  -D FM_RELAY_PIN=2
  -D FM_RELAY_ACTIVE_HIGH=0
  -D FM_LED_PIN=2

[relay_lolin_s2_mini]
build_flags =
  -D FM_RELAY_PIN=16
  -D FM_RELAY_ACTIVE_HIGH=0
  -D FM_LED_PIN=15

[env:esp01_1m]
platform = espressif8266@4.2.1
board = esp01_1m
framework = arduino
board_build.ldscript = eagle.flash.1m64.ld

monitor_speed = 115200
upload_speed = 115200

lib_deps =
  ${common.lib_deps}

build_flags =
  ${common.build_flags}
  ${relay_esp01.build_flags}

[env:esp01_1m_ota]
extends = env:esp01_1m
upload_protocol = espota
upload_port = flatmanager-front-door.local
;upload_flags =
;  --auth=your_ota_password
;  --auth=${sysenv.ESP_OTA_PASSWORD}

extra_scripts = pre:extra_script.py

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem01

lib_deps =
  ${common.lib_deps}

build_flags =
  ${common.build_flags}
  ${relay_lolin_s2_mini.build_flags}

[env:lolin_s2_mini_ota]
extends = env:lolin_s2_mini
upload_protocol = espota
upload_port = flatmanager-front-door.local
extra_scripts = pre:extra_script.py
