#!/usr/bin/env bash
set -euo pipefail

CERT_URL="https://letsencrypt.org/certs/isrgrootx1.pem"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${PROJECT_ROOT}/include"
PEM_FILE="${OUT_DIR}/isrgrootx1.pem"
HEADER_FILE="${OUT_DIR}/root_ca.h"

parse_cert_date_unix() {
  local raw="$1"

  if date -u -d "${raw}" "+%s" >/dev/null 2>&1; then
    date -u -d "${raw}" "+%s"
    return
  fi

  date -u -j -f "%b %e %T %Y %Z" "${raw}" "+%s"
}

parse_cert_date_iso() {
  local raw="$1"

  if date -u -d "${raw}" "+%Y-%m-%dT%H:%M:%SZ" >/dev/null 2>&1; then
    date -u -d "${raw}" "+%Y-%m-%dT%H:%M:%SZ"
    return
  fi

  date -u -j -f "%b %e %T %Y %Z" "${raw}" "+%Y-%m-%dT%H:%M:%SZ"
}

mkdir -p "${OUT_DIR}"

curl -fsSL "${CERT_URL}" -o "${PEM_FILE}"

echo "Certificate info:"
openssl x509 -in "${PEM_FILE}" -noout -subject -issuer -dates

NOT_AFTER_RAW="$(openssl x509 -in "${PEM_FILE}" -noout -enddate | cut -d= -f2-)"
NOT_AFTER_UNIX="$(parse_cert_date_unix "${NOT_AFTER_RAW}")"
NOT_AFTER_ISO="$(parse_cert_date_iso "${NOT_AFTER_RAW}")"

cat > "${HEADER_FILE}" <<EOF
#pragma once

#include <Arduino.h>
#include <time.h>

// ISRG Root X1
// Source: ${CERT_URL}
// Valid until: ${NOT_AFTER_ISO}
// Generated by scripts/update_root_ca.sh

const time_t kRootCaNotAfterUnix = ${NOT_AFTER_UNIX};
const char kRootCaNotAfterIso8601[] = "${NOT_AFTER_ISO}";

const char kRootCa[] PROGMEM = R"EOF_CERT(
$(cat "${PEM_FILE}")
)EOF_CERT";
EOF

echo "Written: ${HEADER_FILE}"


