server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /admin {
    rewrite ^/admin/?(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
