"""create initial schema

Revision ID: 3d3abba05bc0
Revises: 
Create Date: 2026-06-21 01:10:27.171236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d3abba05bc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('booking_reference', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_codes_active'), 'access_codes', ['active'], unique=False)
    op.create_index(op.f('ix_access_codes_apartment_id'), 'access_codes', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_access_codes_valid_from'), 'access_codes', ['valid_from'], unique=False)
    op.create_index(op.f('ix_access_codes_valid_until'), 'access_codes', ['valid_until'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('device_token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('online_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_apartment_id'), 'devices', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_devices_device_token_hash'), 'devices', ['device_token_hash'], unique=True)
    op.create_index(op.f('ix_devices_last_seen'), 'devices', ['last_seen'], unique=False)
    op.create_table('door_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_door_commands_apartment_id'), 'door_commands', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_door_commands_device_id'), 'door_commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_door_commands_expires_at'), 'door_commands', ['expires_at'], unique=False)
    op.create_index(op.f('ix_door_commands_status'), 'door_commands', ['status'], unique=False)
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_code_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ),
    sa.ForeignKeyConstraint(['command_id'], ['door_commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_log_apartment_id'), 'access_log', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_access_log_result'), 'access_log', ['result'], unique=False)
    op.create_index(op.f('ix_access_log_timestamp'), 'access_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_log_timestamp'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_result'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_apartment_id'), table_name='access_log')
    op.drop_table('access_log')
    op.drop_index(op.f('ix_door_commands_status'), table_name='door_commands')
    op.drop_index(op.f('ix_door_commands_expires_at'), table_name='door_commands')
    op.drop_index(op.f('ix_door_commands_device_id'), table_name='door_commands')
    op.drop_index(op.f('ix_door_commands_apartment_id'), table_name='door_commands')
    op.drop_table('door_commands')
    op.drop_index(op.f('ix_devices_last_seen'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_token_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_apartment_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_access_codes_valid_until'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_valid_from'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_apartment_id'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_active'), table_name='access_codes')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
